global:
  scrape_interval: 2s
scrape_configs:
  - job_name: 'fanhub-booking'
    static_configs:
      - targets: ['booking-service:8080']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']